#!/bin/sh
#
#launch script to take mesurements from sensors


case "$1" in
  start)
	printf "Launching script: "
	/root/sensors2db&
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping script: "
	jobid=$(ps | grep -v "grep" | grep sensors2db | egrep -o "[0-9]{2,4}") &&
	kill $jobid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;

  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
